# Generated by Django 4.0.3 on 2022-04-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_hotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.city'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='standard',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
