# Generated by Django 4.0.3 on 2022-04-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_hotel_city_alter_hotel_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
