# Generated by Django 4.0.3 on 2022-04-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_alter_travel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='price',
        ),
    ]
