# Generated by Django 4.0.3 on 2022-04-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_alter_travel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
