# Generated by Django 4.0.3 on 2022-04-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0019_alter_booking_name_alter_booking_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='travel',
        ),
    ]
