# Generated by Django 4.0.3 on 2022-04-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0020_rename_name_booking_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
