# Generated by Django 4.0.3 on 2022-04-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0021_travel_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
