# Generated by Django 4.0.3 on 2022-04-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0022_city_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='type',
        ),
    ]
