# Generated by Django 4.0.3 on 2022-05-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0023_remove_travel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
