# Generated by Django 4.0.3 on 2022-05-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0024_remove_country_code_country_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
